package vista;

import domini.CtrlDomini;
import persistencia.CtrlPersistencia;
import java.awt.Color;
import javax.swing.JButton;

public class VistaMenuPrincipal extends javax.swing.JFrame {
    private CtrlDomini ctrlDomini;

    //para canviar color cuando el mouse deja de apuntar a un boton
    private void mouseSaleRaton(java.awt.event.MouseEvent evt) {
        //devuelve que componente se ve afectado y hacemos cast a JButton(esto
        //último lo podemos hacer pk sabemos seguro que esta funcion solo se invoca
        //sobre JButton's)
        JButton boton = (JButton) evt.getSource();
        boton.setBackground(new Color(60,183,255));
    }

    //para canviar color cuando el mouse apunta a un boton
    private void mouseEntraBoton(java.awt.event.MouseEvent evt) {
        //devuelve que componente se ve afectado y hacemos cast a JButton(esto
        //último lo podemos hacer pk sabemos seguro que esta funcion solo se invoca
        //sobre JButton's)
        JButton boton = (JButton) evt.getSource();

        //le canvio color de fondo
        boton.setBackground(Color.WHITE);
    }

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal(CtrlDomini ctrlDomini) {
        //llama a la generacion automatica de código hecha con el
        //Matisse Netbeans (editor gráfico de Netbeans para GUI)
        initComponents();

        this.ctrlDomini = ctrlDomini;

        /*********************************************************************/
        //A todos los botones les añadimos 2 listeners para que cuando el raton entre o salga, canvien de color
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseSaleRaton(evt);//la funcion que se invoca cuando sale el ratón
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntraBoton(evt);//la funcion que se invoca cuando entra el ratón
            }
        });

        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseSaleRaton(evt);
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntraBoton(evt);
            }
        });

        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseSaleRaton(evt);
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntraBoton(evt);
            }
        });

        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseSaleRaton(evt);
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntraBoton(evt);
            }
        });

        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JButton boton = (JButton) evt.getSource();
                boton.setBackground(new Color(51,204,101));
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntraBoton(evt);
            }
        });

        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseSaleRaton(evt);
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntraBoton(evt);
            }
        });

        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseSaleRaton(evt);
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntraBoton(evt);
            }
        });
        /*********************************************************************/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mastermind");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MAIN MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 40, 260, 81);

        jButton2.setBackground(new java.awt.Color(60, 183, 255));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton2.setText("Guest play");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(180, 45));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 140, 220, 45);

        jButton3.setBackground(new java.awt.Color(60, 183, 255));
        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton3.setText("Create an account");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMaximumSize(new java.awt.Dimension(180, 45));
        jButton3.setMinimumSize(new java.awt.Dimension(180, 45));
        jButton3.setPreferredSize(new java.awt.Dimension(180, 45));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 300, 220, 45);

        jButton4.setBackground(new java.awt.Color(60, 183, 255));
        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton4.setText("Login");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(180, 45));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(300, 220, 220, 45);

        jButton6.setBackground(new java.awt.Color(60, 183, 255));
        jButton6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton6.setText("Ranking");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setMaximumSize(new java.awt.Dimension(180, 45));
        jButton6.setMinimumSize(new java.awt.Dimension(180, 45));
        jButton6.setPreferredSize(new java.awt.Dimension(180, 45));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(300, 390, 220, 45);

        jButton7.setBackground(new java.awt.Color(60, 183, 255));
        jButton7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton7.setText("Records");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(300, 480, 220, 45);

        jButton1.setBackground(new java.awt.Color(60, 183, 255));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setText("How to play ?");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(610, 600, 170, 45);

        jButton5.setBackground(new java.awt.Color(51, 204, 101));
        jButton5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/exit_imagen.png"))); // NOI18N
        jButton5.setText("Exit");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setPreferredSize(new java.awt.Dimension(94, 29));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(30, 610, 170, 45);

        Fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/main_menu.jpg"))); // NOI18N
        getContentPane().add(Fons);
        Fons.setBounds(0, 0, 800, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //boton "EXIT"
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //sortim d'aplicació
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    //boton "Login"
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //ensenya VistaLogin, NO cal tenir en aquesta classe una variable privada que guardi la vista
        //ja que 'VistaLogin.main(null);' és un métode estàtic(no cal una instancia de classe per cridar-lo)
        //que ja s'encarrega ell de crear i mostrar la vista
        VistaLogin.main(null, ctrlDomini);

    }//GEN-LAST:event_jButton4ActionPerformed

    //botón 'create account'
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //ensenya VistaCrearCompte, NO cal tenir en aquesta classe una variable privada que guardi la vista
        //ja que 'VistaLogin.main(null);' és un métode estàtic(no cal una instancia de classe per cridar-lo)
        //que ja s'encarrega ell de crear i mostrar la vista
        VistaCrearCompte.main(null, ctrlDomini);
    }//GEN-LAST:event_jButton3ActionPerformed

    //botó "Ranking"
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        VistaEscollirRanking.main(null, ctrlDomini);
    }//GEN-LAST:event_jButton6ActionPerformed

    //botó "Records"
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        VistaEscollirRecord.main(null, ctrlDomini);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
		CtrlPersistencia pers = new CtrlPersistencia();
		System.out.println("entrat a jbutton1");
		pers.mostrarManual();
	}
    //botó "Guest play"
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VistaOpcions.main(null, ctrlDomini, null);//3r paràmetre null per indicar que es el convidat
                                                  //qui jugarà o mirarà partida
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], CtrlDomini ctrlDomini) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VistaMenuPrincipal(ctrlDomini).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fons;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
