package vista;

import domini.CtrlDomini;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VistaCrearCompte extends javax.swing.JDialog {
    CtrlDomini ctrlDomini;

    private String username;
    private String password;
    private String confirmPassword;
    private String nomPublic;



    public VistaCrearCompte(java.awt.Frame parent, boolean modal, CtrlDomini ctrlDomini) {
        super(parent, modal);
        initComponents();

        this.ctrlDomini = ctrlDomini;
        username = "";
        password = "";
        confirmPassword = "";
        nomPublic = "";

        /******************************************************************/
        // A cada camp d' entrada de text li "diem" quina funció cridar quan l'usuari prem enter
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                //si s'ha premut tecla enter
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    username = jTextField1.getText();
                    if (username.equals("")) {
                        JOptionPane.showMessageDialog(new JFrame(),
                                                      "The username can not be empty",
                                                      "ERROR",
                                                      JOptionPane.ERROR_MESSAGE);
                    }
                    else jTextField2.requestFocus();
                }

            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                //si s'ha premut tecla enter
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    password = jTextField2.getText();
                    jTextField3.requestFocus();
                }
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                //si s'ha premut tecla enter
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    confirmPassword = jTextField3.getText();
                    if (password.equals(confirmPassword)) jTextField4.requestFocus();
                    else {
                        JOptionPane.showMessageDialog(new JFrame(),
                                                      "Both passwords must be identical",
                                                      "ERROR",
                                                      JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                //si s'ha premut tecla enter
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    nomPublic = jTextField4.getText();
                    if (nomPublic.equals("")) {
                        JOptionPane.showMessageDialog(new JFrame(),
                                                      "The public name can not be empty",
                                                      "ERROR",
                                                      JOptionPane.ERROR_MESSAGE);
                    }
                    else jButton1.doClick();
                }
            }
        });
        /******************************************************************/
        //mostrem breu info explicant cada camp
        String text = "Username and password are for Login\n";
        text += "Public name will be shown in Ranking and Records(is your 'name' in the game)";

        JOptionPane.showMessageDialog(new JFrame(), //un nou frame on mostrar
                                        text, //el text que es mostrarà
                                        "Information", //el títol del diàleg
                                        JOptionPane.INFORMATION_MESSAGE);//el tipus d'icona

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(547, 427));
        setSize(new java.awt.Dimension(547, 427));

        jPanel1.setBackground(new java.awt.Color(53, 159, 238));
        jPanel1.setMaximumSize(new java.awt.Dimension(547, 427));
        jPanel1.setMinimumSize(new java.awt.Dimension(547, 427));
        jPanel1.setSize(new java.awt.Dimension(547, 427));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm password");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Public name");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 102));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 80, 66));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addGap(35, 35, 35))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(14, 14, 14))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //quan apretem botó "ok"
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        username = jTextField1.getText();
        password = jTextField2.getText();
        confirmPassword = jTextField3.getText();
        nomPublic = jTextField4.getText();

        if (username.equals("")) {
            JOptionPane.showMessageDialog(new JFrame(),
                                          "The username can not be empty",
                                          "ERROR",
                                          JOptionPane.ERROR_MESSAGE);
        }
        if (nomPublic.equals("")) {
            JOptionPane.showMessageDialog(new JFrame(),
                                          "The public name can not be empty",
                                          "ERROR",
                                          JOptionPane.ERROR_MESSAGE);
        }
        if (! password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(new JFrame(),
                                          "Both passwords must be identical",
                                          "ERROR",
                                          JOptionPane.ERROR_MESSAGE);
        }
        //tot correcte, intentem crear nou JugadorRegistrat
        else {
            try {
                boolean ok = ctrlDomini.afegirJugadorRegistrat(nomPublic, username, password);
                if (ok) {
                    //JOptionPane.showMessageDialog(new JFrame(), "Account created\nYou must remember Username and password");
                    JOptionPane.showMessageDialog(new JFrame(),
                                                    "Account created\nYou must remember Username and password",
                                                    "Message",
                                                    JOptionPane.INFORMATION_MESSAGE);
                    ctrlDomini.guardarJugadors();
                    dispose();
                }
                else {
                    JOptionPane.showMessageDialog(new JFrame(), "Sorry, try a different Username or Public name");
                }

            } catch (Exception ex) {
                Logger.getLogger(VistaCrearCompte.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //que fem quan es prem el botó cancel
    //el que fem es mostrar un quadre dialeg confirmant que es vol sortir, no sigui
    //que l'usuari hagi omplert to el formulari i tiri enrere sense voler
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //font d'informació-> documentació oficial :)
        //https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html#features
        //https://docs.oracle.com/javase/7/docs/api/javax/swing/JOptionPane.html#constructor_summary
        //les nostres opcions:
        Object[] options = { "Yes", "No" };
        // the showMessageDialog, showConfirmDialog, and showOptionDialog methods
        //return an integer indicating the user's choice
        //The values for this integer are YES_OPTION, NO_OPTION, CANCEL_OPTION,
        //OK_OPTION, and CLOSED_OPTION. Except for CLOSED_OPTION, each option corresponds
        //to the button the user pressed. When CLOSED_OPTION is returned,
        //it indicates that the user closed the dialog window explicitly,
        //rather than by choosing a button inside the option pane.
        int n = JOptionPane.showOptionDialog(null,
            "Are you sure you want to cancel", //->missatge que es mostrarà
            "Warning", //->títol del cuadre de dialeg que es mostrarà
            JOptionPane.YES_NO_CANCEL_OPTION, //tipus d'opcions mostrades
            JOptionPane.QUESTION_MESSAGE, //icona de 'question'(pregunta)
            null, //no usar icona personalitzat
            options, //els titols dels butons
            options[1]); //quin té el focus(iluminat)

        if (n == JOptionPane.YES_OPTION) dispose();
    }//GEN-LAST:event_jButton2ActionPerformed



    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        username = jTextField1.getText();
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        password = jTextField2.getText();
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        confirmPassword = jTextField3.getText();
        if (! password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(new JFrame(),
                                          "Both passwords must be identical",
                                          "ERROR",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        nomPublic = jTextField4.getText();
    }//GEN-LAST:event_jTextField4FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], CtrlDomini ctrlDomini) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCrearCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCrearCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCrearCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCrearCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaCrearCompte dialog = new VistaCrearCompte(new javax.swing.JFrame(), true, ctrlDomini);
                /* lo comentat es pot eliminar, sinó al apretar x de tancar finestra de crear compte es tanca tota la
                   aplicació, cosa que no volem, nomes volem que el formulari desaparegui
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                */
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
