package vista;

import domini.CtrlDomini;
import domini.ModelTaulell;
import domini.RegistreTaulells;
import java.awt.Color;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

public class VistaSelectBoard extends javax.swing.JDialog {
        /**
    	 *Model de taulell seleccionat que es representa
	 */
    private static ModelTaulell mt;
	/**
	 *Copia del registre de taulells
	 */
    private RegistreTaulells rt;
        /**
         * ID del taulell seleccionat
         */
    private int id;
    /**
	 *Jpanel que representa l'espai ocupat per la representacio del taulell
	 */
    private JPanel board;

    private VistaOpcions vo;

    private CtrlDomini ctrlDomini;

    /**
	 * Configura el registre de taulells
	 *@param registre es el registre usat
	 */
    public void setRegistreTaulells (RegistreTaulells registre){
        try {
            rt= registre;
            mt=rt.getTaulell(0);
            id=0;
        } catch (Exception ex) {
            System.err.println("Exception: "+ex.getMessage());
        }

    }

    private CirclePanel drawCircle(int size, String color, int posX, int posY, String name){
        CirclePanel aux = new CirclePanel();
        aux.setForeground(Color.decode(color));
        aux.setFocusable(false);
        aux.setName(name);
        aux.setOpaque(true);
        aux.setSize(size,size);
        aux.setLocation(posX,posY);
        return aux;
    }
    private ImagePanel drawImage(int w, int h, String path, int posX, int posY, String name){
        ImagePanel aux = new ImagePanel();
        aux.setImg(path);
        aux.setFocusable(false);
        aux.setName(name);
        aux.setOpaque(true);
        aux.setSize(w,h);
        aux.setLocation(posX,posY);
        return aux;
    }

    private void updateBoard(){
        representacioTaulell.removeAll();
        representacioTaulell.repaint();
        representacioTaulell.setLayout(null);

        int numEsp=mt.getAmplada();
        int panelH= representacioTaulell.getHeight()-12;
        int panelW= representacioTaulell.getWidth()-18;
        int sizeX =Math.min((int) panelW/numEsp,panelW/7);
        int sizeY= (int) panelH/mt.getAlcada();

        int size=Math.min(sizeX, sizeY);

        board=new JPanel();
        board.setLocation(9+(panelW-numEsp*size)/2,6);
        board.setSize(numEsp*size,panelH);
        board.setOpaque(false);
        board.setLayout(null);
        representacioTaulell.add(board);
        String path="/vista/hole.png";
         for(int i=0; i<mt.getAmplada(); ++i){
            for(int j=0; j<mt.getAlcada(); ++j){
                ImagePanel aux = drawImage(size,size,path,i*size,panelH-(j+1)*size,"pos"+i+j);
                board.add(aux);
            }
        }

    }


        private void updateColors(){
        colors1.removeAll();
        colors1.repaint();
        //colors1.setLayout(null);
        colors2.removeAll();
        colors2.repaint();
        //colors2.setLayout(null);
        for(int i=0;i<mt.getNColors();++i){
           if(i<4){
            CirclePanel aux = drawCircle(36, mt.getColors().get(i),2,2+45*i,"col"+i);
            CirclePanel back = drawCircle(40, "#000000",0,45*i,"back"+i);
            colors1.add(aux);
            colors1.add(back);
           }
           else{
            CirclePanel aux = drawCircle(36, mt.getColors().get(i),2,2+45*(i%4),"col"+i);
            CirclePanel back = drawCircle(40, "#000000",0,45*(i%4),"back"+i);
            colors2.add(aux);
            colors2.add(back);
           }

        }
    }
    /*public ModelTaulell returnModel(){
        return mt;
    }*/
    /**
     * Creates new form VistaSelectBoard
     */
    public VistaSelectBoard(java.awt.Frame parent, boolean modal, VistaOpcions vo, CtrlDomini ctrlDomini) throws Exception {
        super(parent, modal);
        initComponents();
        this.ctrlDomini = ctrlDomini;
        this.vo = vo;
        rt = ctrlDomini.getTaulells();
        mt=rt.getTaulell(0);
        updateBoard();
        updateColors();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        representacioTaulell = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nextB = new javax.swing.JButton();
        selectB = new javax.swing.JButton();
        colors2 = new javax.swing.JPanel();
        colors1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(5, 8, 237));
        setForeground(new java.awt.Color(0, 10, 255));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(56, 60, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));

        representacioTaulell.setBackground(new java.awt.Color(99, 97, 100));
        representacioTaulell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 47, 60), 5));
        representacioTaulell.setMaximumSize(new java.awt.Dimension(300, 360));
        representacioTaulell.setPreferredSize(new java.awt.Dimension(300, 360));

        javax.swing.GroupLayout representacioTaulellLayout = new javax.swing.GroupLayout(representacioTaulell);
        representacioTaulell.setLayout(representacioTaulellLayout);
        representacioTaulellLayout.setHorizontalGroup(
            representacioTaulellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(representacioTaulellLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8))
        );
        representacioTaulellLayout.setVerticalGroup(
            representacioTaulellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(representacioTaulellLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel8))
        );

        nextB.setText("Next");
        nextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBActionPerformed(evt);
            }
        });

        selectB.setText("Select");
        selectB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBActionPerformed(evt);
            }
        });

        colors2.setOpaque(false);

        javax.swing.GroupLayout colors2Layout = new javax.swing.GroupLayout(colors2);
        colors2.setLayout(colors2Layout);
        colors2Layout.setHorizontalGroup(
            colors2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        colors2Layout.setVerticalGroup(
            colors2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        colors1.setOpaque(false);

        javax.swing.GroupLayout colors1Layout = new javax.swing.GroupLayout(colors1);
        colors1.setLayout(colors1Layout);
        colors1Layout.setHorizontalGroup(
            colors1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        colors1Layout.setVerticalGroup(
            colors1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectB, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(nextB)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(colors1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(representacioTaulell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(colors2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(colors2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextB)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(representacioTaulell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(selectB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(colors1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBActionPerformed
        try {
            // TODO add your handling code here:
            HashMap hm= rt.getTaulells();
            id++;
            id=id%(rt.getNextId());
            while(!hm.containsKey(id)){
                id=id%(rt.getNextId());
            }
            mt=rt.getTaulell(id);
            updateBoard();
            updateColors();
        } catch (Exception ex) {
            System.err.println("Exception: "+ex.getMessage());
        }
    }//GEN-LAST:event_nextBActionPerformed

    private void selectBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBActionPerformed
        vo.setModelTaulell(mt);
        dispose();
    }//GEN-LAST:event_selectBActionPerformed



    /**
     * @param args the command line arguments
     */
    public static ModelTaulell main(String args[], VistaOpcions vo, CtrlDomini ctrlDomini) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSelectBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSelectBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSelectBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSelectBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    VistaSelectBoard dialog = new VistaSelectBoard(new javax.swing.JFrame(), true, vo, ctrlDomini);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            //System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VistaSelectBoard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        return mt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colors1;
    private javax.swing.JPanel colors2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextB;
    private javax.swing.JPanel representacioTaulell;
    private javax.swing.JButton selectB;
    // End of variables declaration//GEN-END:variables
}
