package vista;

public class VistaGuardarPartida extends javax.swing.JDialog {

    int currentOption = 0;
   private static boolean estaGuardant;
    /**
    * VistaCrearTaulell que l'ha creat
    */
    private static VistaPartida pare;

    private static VistaUsuariLogejat pare2;
    /**
      * Defineix el pare
      * @param v Es el que s'assignara a pare
      */
    public static void setParent(VistaPartida v){
        pare=v;
    }

    public static void setParent2(VistaUsuariLogejat v){
        pare2=v;
    }
    public static void setEstaGuardant(boolean b){
		estaGuardant=b;
	}

    /**
     * Creates new form VistaGuardarPartida
     */
    public VistaGuardarPartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slotGuardar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        sortirButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        slotNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 280));
        setMinimumSize(new java.awt.Dimension(400, 280));
        setPreferredSize(new java.awt.Dimension(400, 280));
        setResizable(false);
        getContentPane().setLayout(null);

        slotGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		slotGuardar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"0", "1", "2" }));
        slotGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(slotGuardar);
        slotGuardar.setBounds(240, 120, 70, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        if(estaGuardant) jLabel1.setText("A on vols guardar la partida?");
		else jLabel1.setText("Quina partida vols carregar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 330, 70);

        sortirButton.setText("Sortir");
        sortirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sortirButton);
        sortirButton.setBounds(90, 200, 59, 23);

        if(estaGuardant) guardarButton.setText("Guardar i Sortir");
		else guardarButton.setText("Carregar i Sortir");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(guardarButton);
        guardarButton.setBounds(220, 190, 105, 40);

        slotNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        slotNameLabel.setText("Slot 0");
        getContentPane().add(slotNameLabel);
        slotNameLabel.setBounds(90, 120, 60, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortirButtonActionPerformed
        dispose();
    }//GEN-LAST:event_sortirButtonActionPerformed

    private void slotGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotGuardarActionPerformed
        currentOption = slotGuardar.getSelectedIndex();
        slotNameLabel.setText("Slot " + String.valueOf(currentOption));
    }//GEN-LAST:event_slotGuardarActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
		if(estaGuardant) pare.slotPartida(currentOption);
		else pare2.slotPartida(currentOption);
		dispose();
    }//GEN-LAST:event_guardarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGuardarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGuardarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGuardarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGuardarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaGuardarPartida dialog = new VistaGuardarPartida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    /*@Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }*/
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> slotGuardar;
    private javax.swing.JLabel slotNameLabel;
    private javax.swing.JButton sortirButton;
    // End of variables declaration//GEN-END:variables
}
