package vista;

import domini.CtrlDomini;
import java.awt.Color;
import javax.swing.JButton;

public class VistaPantallaBenvinguda extends javax.swing.JFrame {
    private CtrlDomini ctrlDomini;

    //para canviar color cuando el mouse deja de apuntar a un boton
    private void mouseSaleRaton(java.awt.event.MouseEvent evt) {
        JButton boton = (JButton) evt.getSource();
        boton.setBackground(Color.BLACK);

        //boton.setForeground(Color.BLACK);
    }

    //para canviar color cuando el mouse apunta a un boton
    private void mouseEntraBoton(java.awt.event.MouseEvent evt) {
        //devuelve que componente se ve afectado y hacemos cast a JButton(esto
        //último lo podemos hacer pk sabemos seguro que esta funcion solo se invoca
        //sobre JButton's)
        JButton boton = (JButton) evt.getSource();

        //le canvio color de fondo

        //boton.setBackground(Color.BLACK);

        boton.setBackground(new Color(0,0,156));
    }

    /**
     * Creates new form VistaPantallaBenvinguda
     */
    public VistaPantallaBenvinguda(CtrlDomini ctrlDomini) {
        initComponents();
        this.ctrlDomini = ctrlDomini;

        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseSaleRaton(evt);
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntraBoton(evt);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1024, 641));
        setPreferredSize(new java.awt.Dimension(1024, 641));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 641));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 641));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 641));
        jPanel1.setSize(new java.awt.Dimension(1024, 641));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Andale Mono", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME TO MASTERMIND");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 590, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Superclarendon", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("START");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 230, 240, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/cerebro_mastermind.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1018, 649);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 1024, 641);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //botó "Start" apretat
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaMenuPrincipal.main(null, ctrlDomini);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], CtrlDomini ctrlDomini) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPantallaBenvinguda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPantallaBenvinguda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPantallaBenvinguda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPantallaBenvinguda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPantallaBenvinguda(ctrlDomini).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
